package learn.secops.data;

import learn.secops.models.EventType;
import learn.secops.models.SecurityEvent;
import learn.secops.models.Severity;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.postgresql.ds.PGSimpleDataSource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Given, complete -- do not edit this file. Point your
 * SECOPS_DB_PASSWORD and a local "secops_event_exercise_test"
 * database at this before running `mvn test`.
 */
class SecurityEventRepositoryTest {

    private final DataSource dataSource = buildDataSource();
    private final JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
    private final SecurityEventRepository repository = new SecurityEventJdbcTemplateRepository(jdbcTemplate);

    @BeforeEach
    void resetKnownGoodState() throws SQLException {
        try (Connection conn = dataSource.getConnection()) {
            ScriptUtils.executeSqlScript(conn, new ClassPathResource("schema.sql"));
            ScriptUtils.executeSqlScript(conn, new ClassPathResource("data.sql"));
        }
    }

    @Test
    void shouldFindAll() {
        assertEquals(4, repository.findAll().size());
    }

    @Test
    void shouldFindByHostId() {
        assertEquals(2, repository.findByHostId(1).size());
    }

    @Test
    void shouldFindUnacknowledged() {
        List<SecurityEvent> unacknowledged = repository.findUnacknowledged();
        assertEquals(3, unacknowledged.size());
        assertTrue(unacknowledged.stream().noneMatch(SecurityEvent::isAcknowledged));
    }

    @Test
    void shouldFindById() {
        SecurityEvent event = repository.findById(1);
        assertNotNull(event);
        assertEquals(EventType.PORT_SCAN, event.getEventType());
        assertEquals(Severity.MEDIUM, event.getSeverity());
        assertFalse(event.isAcknowledged());
    }

    @Test
    void shouldReturnNullWhenIdMissing() {
        assertNull(repository.findById(9999));
    }

    @Test
    void shouldAdd() {
        SecurityEvent event = new SecurityEvent(2, EventType.UNAUTHORIZED_ACCESS, Severity.HIGH,
                "Privileged account used outside business hours");

        SecurityEvent actual = repository.add(event);

        assertNotNull(actual);
        assertTrue(actual.getEventId() > 0);
        assertFalse(actual.isAcknowledged());
    }

    @Test
    void shouldAcknowledge() {
        assertTrue(repository.acknowledge(1));

        SecurityEvent reloaded = repository.findById(1);
        assertTrue(reloaded.isAcknowledged());
        assertNotNull(reloaded.getAcknowledgedAt());
    }

    @Test
    void shouldNotAcknowledgeAlreadyAcknowledgedEvent() {
        // event 2 is already acknowledged in the seed data
        SecurityEvent before = repository.findById(2);
        LocalDateTime originalAcknowledgedAt = before.getAcknowledgedAt();

        assertFalse(repository.acknowledge(2));

        SecurityEvent after = repository.findById(2);
        assertEquals(originalAcknowledgedAt, after.getAcknowledgedAt(),
                "acknowledging an already-acknowledged event must not overwrite the original timestamp");
    }

    @Test
    void shouldNotAcknowledgeMissingEvent() {
        assertFalse(repository.acknowledge(9999));
    }

    @Test
    void shouldDeleteExisting() {
        assertTrue(repository.deleteById(4));
    }

    @Test
    void shouldNotDeleteMissing() {
        assertFalse(repository.deleteById(9999));
    }

    private static DataSource buildDataSource() {
        PGSimpleDataSource ds = new PGSimpleDataSource();
        ds.setServerNames(new String[]{"localhost"});
        ds.setPortNumbers(new int[]{5432});
        ds.setDatabaseName("secops_event_exercise_test");
        ds.setUser("secops_app");
        ds.setPassword(System.getenv("SECOPS_DB_PASSWORD"));
        return ds;
    }
}
