CREATE TABLE IF NOT EXISTS vehicle (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vin VARCHAR(17) NOT NULL UNIQUE CHECK (char_length(vin)=17),
  description VARCHAR(200) NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('AVAILABLE','RENTED','SERVICE'))
);
