package learn.secops.models;

import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Given, complete -- do not edit this file.
 *
 * Notice this test class needs no database, no Spring context, and
 * no JdbcTemplate. That's only possible because SecurityEvent
 * enforces its own rules regardless of where it came from -- a
 * repository is not the only thing standing between this object and
 * an invalid state.
 */
class SecurityEventTest {

    @Test
    void shouldRejectNonPositiveHostId() {
        assertThrows(IllegalArgumentException.class,
                () -> new SecurityEvent(0, EventType.PORT_SCAN, Severity.LOW, "test"));
    }

    @Test
    void shouldRejectNullEventType() {
        assertThrows(IllegalArgumentException.class,
                () -> new SecurityEvent(1, null, Severity.LOW, "test"));
    }

    @Test
    void shouldRejectNullSeverity() {
        assertThrows(IllegalArgumentException.class,
                () -> new SecurityEvent(1, EventType.PORT_SCAN, null, "test"));
    }

    @Test
    void shouldRejectBlankDescription() {
        assertThrows(IllegalArgumentException.class,
                () -> new SecurityEvent(1, EventType.PORT_SCAN, Severity.LOW, "   "));
    }

    @Test
    void shouldRejectAcknowledgedWithoutAcknowledgedAt() {
        assertThrows(IllegalArgumentException.class,
                () -> new SecurityEvent(1, 1, EventType.PORT_SCAN, Severity.LOW,
                        "test", LocalDateTime.now(), true, null));
    }

    @Test
    void shouldRejectAcknowledgedAtWithoutAcknowledged() {
        assertThrows(IllegalArgumentException.class,
                () -> new SecurityEvent(1, 1, EventType.PORT_SCAN, Severity.LOW,
                        "test", LocalDateTime.now(), false, LocalDateTime.now()));
    }

    @Test
    void newEventShouldStartUnacknowledged() {
        SecurityEvent event = new SecurityEvent(1, EventType.PORT_SCAN, Severity.LOW, "test");
        assertFalse(event.isAcknowledged());
        assertNull(event.getAcknowledgedAt());
    }

    @Test
    void acknowledgeShouldReturnANewInstanceAndLeaveTheOriginalUnchanged() {
        SecurityEvent original = new SecurityEvent(1, EventType.PORT_SCAN, Severity.LOW, "test");

        SecurityEvent acknowledged = original.acknowledge();

        assertFalse(original.isAcknowledged(), "the original instance must be unaffected");
        assertTrue(acknowledged.isAcknowledged());
        assertNotNull(acknowledged.getAcknowledgedAt());
    }

    @Test
    void acknowledgeShouldRejectAnAlreadyAcknowledgedEvent() {
        SecurityEvent acknowledged = new SecurityEvent(1, EventType.PORT_SCAN, Severity.LOW, "test")
                .acknowledge();

        assertThrows(IllegalStateException.class, acknowledged::acknowledge);
    }
}
