spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=ledgercore

spring.main.web-application-type=none
spring.main.banner-mode=off

logging.threshold.console=OFF
logging.file.name=logs/ledger.log
logging.level.root=INFO
logging.level.demo.ledger=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
