package learn.secops.data;

import learn.secops.models.Service;
import learn.secops.models.ServiceStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.postgresql.ds.PGSimpleDataSource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Given, complete -- do not edit this file. Point your
 * SECOPS_DB_PASSWORD and a local "secops_exercise_test" database at
 * this before running `mvn test`.
 */
class ServiceJdbcTemplateRepositoryTest {

    private final DataSource dataSource = buildDataSource();
    private final JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
    private final ServiceRepository repository = new ServiceJdbcTemplateRepository(jdbcTemplate);

    @BeforeEach
    void resetKnownGoodState() throws SQLException {
        try (Connection conn = dataSource.getConnection()) {
            ScriptUtils.executeSqlScript(conn, new ClassPathResource("schema.sql"));
            ScriptUtils.executeSqlScript(conn, new ClassPathResource("data.sql"));
        }
    }

    @Test
    void shouldFindAll() {
        List<Service> services = repository.findAll();
        assertEquals(4, services.size());
    }

    @Test
    void shouldFindByHostId() {
        List<Service> services = repository.findByHostId(1);
        assertEquals(2, services.size());
    }

    @Test
    void shouldFindById() {
        Service service = repository.findById(1);
        assertNotNull(service);
        assertEquals("nginx", service.getName());
        assertEquals(443, service.getPort());
        assertEquals(ServiceStatus.RUNNING, service.getStatus());
    }

    @Test
    void shouldReturnNullWhenIdMissing() {
        assertNull(repository.findById(9999));
    }

    @Test
    void shouldAdd() {
        Service service = new Service(2, "cron", 1, ServiceStatus.UNKNOWN);

        Service actual = repository.add(service);

        assertNotNull(actual);
        assertTrue(actual.getServiceId() > 0);
        assertEquals("cron", actual.getName());
    }

    @Test
    void shouldUpdateExisting() {
        Service service = repository.findById(4);
        service.setStatus(ServiceStatus.RUNNING);

        assertTrue(repository.update(service));
        assertEquals(ServiceStatus.RUNNING, repository.findById(4).getStatus());
    }

    @Test
    void shouldNotUpdateMissing() {
        Service service = new Service(9999, 1, "ghost", 22, ServiceStatus.UNKNOWN);
        assertFalse(repository.update(service));
    }

    @Test
    void shouldDeleteExisting() {
        assertTrue(repository.deleteById(4));
    }

    @Test
    void shouldNotDeleteMissing() {
        assertFalse(repository.deleteById(9999));
    }

    private static DataSource buildDataSource() {
        PGSimpleDataSource ds = new PGSimpleDataSource();
        ds.setServerNames(new String[]{"localhost"});
        ds.setPortNumbers(new int[]{5432});
        ds.setDatabaseName("secops_exercise_test");
        ds.setUser("secops_app");
        ds.setPassword(System.getenv("SECOPS_DB_PASSWORD"));
        return ds;
    }
}
